version: 0.0
Resources:
  - blueGreenLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "blue-green-lambda"
        Alias: "live"
        CurrentVersion: "{{CURRENT_VERSION}}"
        TargetVersion: "{{TARGET_VERSION}}"
