Parameters:
  LambdaExecutionRoleArn:
    Description: ARN of the Lambda execution role
    Type: String
  CodeDeployServiceRoleArn:
    Description: ARN of the CodeDeploy service role
    Type: String
  LambdaFunctionName:
    Description: Name of the Lambda function
    Type: String
  CodeDeployApplicationName:
    Description: Name of the CodeDeploy application
    Type: String
  DeploymentGroupName:
    Description: Name of the CodeDeploy deployment group
    Type: String
  S3BucketName:
    Description: Name of the S3 bucket containing Lambda code
    Type: String
  S3Key:
    Description: Key of the Lambda code in S3 bucket
    Type: String

Resources:
  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: !Ref CodeDeployApplicationName
      ComputePlatform: Lambda

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Handler: lambda_function.lambda_handler
      Role: !Ref LambdaExecutionRoleArn
      Runtime: python3.8
      Timeout: 15
      MemorySize: 128
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: !Ref S3Key

  LambdaVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref LambdaFunction

  LambdaAlias:
    Type: AWS::Lambda::Alias
    Properties:
      Name: live
      FunctionName: !Ref LambdaFunction
      FunctionVersion: !GetAtt LambdaVersion.Version

  CodeDeployDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApplication
      DeploymentGroupName: !Ref DeploymentGroupName
      ServiceRoleArn: !Ref CodeDeployServiceRoleArn
      DeploymentConfigName: CodeDeployDefault.LambdaAllAtOnce
      DeploymentStyle:
        DeploymentType: BLUE_GREEN
        DeploymentOption: WITH_TRAFFIC_CONTROL
      AutoRollbackConfiguration:
        Enabled: true
        Events:
          - DEPLOYMENT_FAILURE
