Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: blue-green-lambda
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::767397768513:role/Jenkins-Lambda
      Runtime: python3.8
      Timeout: 15
      MemorySize: 128
      Code:
        S3Bucket: s3-jenkins-lambda
        S3Key: lambda_function.zip

  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ComputePlatform: Lambda

  CodeDeployDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApplication
      DeploymentConfigName: CodeDeployDefault.LambdaAllAtOnce
      ServiceRoleArn: arn:aws:iam::767397768513:role/Jenkins-Lambda
      DeploymentStyle:
        DeploymentType: BLUE_GREEN
